[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "your_production_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_production_supabase_anon_key"
  VITE_STRIPE_PUBLISHABLE_KEY = "your_production_stripe_key"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "your_preview_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_preview_supabase_anon_key"

[context.branch-deploy.environment]
  VITE_SUPABASE_URL = "your_development_supabase_url"
  VITE_SUPABASE_ANON_KEY = "your_development_supabase_anon_key"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"